[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd frontend && yarn install"]

[phases.build]
cmds = ["cd frontend && yarn build"]

[start]
cmd = "cd frontend && npx serve -s build -l ${PORT:-3000}"
